"""add is_free gating to sections and mock_tests

Revision ID: 0ac788a88bf2
Revises: b33a89c6a028
Create Date: 2026-06-20 16:03:57.103369

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0ac788a88bf2'
down_revision: str | None = 'b33a89c6a028'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'mock_tests',
        sa.Column(
            'is_free', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column(
        'sections',
        sa.Column(
            'is_free', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'is_free')
    op.drop_column('mock_tests', 'is_free')
    # ### end Alembic commands ###
